#include <iostream>
#include <opencv2/opencv.hpp>
#include <string>

#include "VersionConfig.h"  //This file will be generated by cmake. By processing VersionConfig.in.h

int main(int argc, char* argv[]) {
  std::cout << "vgen Version"
            << " " << VERSION_MAJOR << "." << VERSION_MINOR << "."
            << VERSION_PATCH << std::endl;

  // We need one argument. The file from which we will generate a video.
  if (argc != 2) {
    std::cout << "Usage: vgen <filename>" << std::endl;
    return -1;
  }

  Mat image;
  image = imread("sample.jpg");
  if (!image.data) {
    printf("No image data \n");
    return -1;
  }
  namedWindow("Display Image", WINDOW_AUTOSIZE);
  imshow("Display Image", image);
  waitKey(0);
}
